# the gpt2 train tokenizer always appends <|endoftext|>
# as end of sequence token
tokenize:
  type: huggingface
  name: relpath(gpt2/tokenizer.json)
special:
  tokens:
    - <|endoftext|>
  pad: <|endoftext|>
  suffix:
    - <|endoftext|>
