# the t5 output tokenizer always prepends <pad>
# as start of sequence token during decoding
tokenize:
  type: huggingface
  name: env(T5_MODEL:t5-small)
special:
  tokens: 
    - <pad>
  pad: <pad>
  prefix:
    - <pad>
