port: 40000
timeout: 10
# precision: fp16
# allow_origin: test.mydomain.com 
feedback_file: env(FEEDBACK_FILE:feedback.jsonl)
base_url: env(BASE_URL:/api)
models:
  # load a pretrained model by specifying the name
  # - name: pretrained_model
  # load a model from a local experiment by specifying the
  # directory path (you can use special configuration operators,
  # e.g. env(ENV_VAR) to load env variables)
  - path: env(EXPERIMENT)
    entity_index: env(SPARQL_PREFIX_INDEX)/entities.bin
    property_index: env(SPARQL_PREFIX_INDEX)/properties.bin
    example_index: env(SPARQL_EXAMPLE_INDEX:null)
