limit: env(BENCHMARK_LIMIT:128)
entity_index: data/prefix-index/env(KG:wikidata)-entities.bin
property_index: data/prefix-index/env(KG:wikidata)-properties.bin
search: env(SEARCH:beam)
beam_width: env(BEAM_WIDTH:4)
batch_size: eval(env(BATCH_LIMIT:8) // env(BEAM_WIDTH:4))
kg: env(KG:wikidata)
log_n_samples: env(BENCHMARK_LOG_N:8)
